"""Remove redundant/placeholder comments in non-Python languages.

Copyright (c) 2026 PyNEAT Authors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, contact: license@pyneat.dev
"""

import re
from typing import List, Tuple

from pyneat.rules.multilang.base import MultilangCleanRule
from pyneat.core.types import CodeFile, TransformationResult


# Language-specific comment prefixes
_COMMENT_PREFIXES = {
    "javascript": ("//", "/*", "*/"),
    "typescript": ("//", "/*", "*/"),
    "go": ("//", "/*", "*/"),
    "java": ("//", "/*", "*/"),
    "rust": ("//", "/*", "*/"),
    "csharp": ("//", "/*", "*/"),
    "php": ("//", "#", "/*", "*/"),
    "ruby": ("#", "=begin", "=end"),
}


def _is_redundant_comment(text: str, lang: str) -> bool:
    """Check if a comment is redundant/empty/placeholder."""
    t = text.strip()
    if not t:
        return True

    prefixes = _COMMENT_PREFIXES.get(lang, ("//",))

    # Detect single-line comment prefix
    line_prefix = None
    for p in prefixes:
        if t.startswith(p):
            line_prefix = p
            break

    if line_prefix:
        content = t[len(line_prefix):].strip()
        if not content:
            return True

        # Empty TODO/FIXME markers
        markers = ["TODO", "FIXME", "HACK", "XXX", "NOTE", "BUG"]
        for marker in markers:
            if re.match(rf"^{re.escape(marker)}\s*:?\s*$", content, re.IGNORECASE):
                return True

        # Placeholder fillers
        if re.match(r"^(\.{2,}|_{2,}|--+|==+)$", content):
            return True

        # AI boilerplate
        ai_phrases = [
            "generated by", "AI-generated", "created by AI",
            "written by AI", "AI assistant",
        ]
        for phrase in ai_phrases:
            if phrase.lower() in content.lower():
                return True

        # Filler phrases
        filler_phrases = ["fill in", "placeholder", "my ideal", "my plan"]
        for phrase in filler_phrases:
            if phrase.lower() in content.lower():
                return True

    # Multi-line block comment: `/* */`
    block_langs = ("javascript", "typescript", "java", "rust", "csharp", "php", "go")
    if lang in block_langs and t.startswith("/*") and t.endswith("*/"):
        inner = t[2:-2].strip()
        if not inner:
            return True
        # Short or placeholder content
        placeholder_words = [
            "empty", "placeholder", "delete this", "remove this",
            "FIXME", "TODO", "HACK",
        ]
        inner_lower = inner.lower()
        if any(w.lower() in inner_lower for w in placeholder_words):
            return True

    return False


class RedundantCommentRule(MultilangCleanRule):
    """Remove redundant and placeholder comments.

    Uses LN-AST's `comments` field to identify and remove comments
    that are empty, markers-only, or AI-generated boilerplate.

    Preserves:
      - Comments with actual content
      - License headers
      - Documentation comments

    Supported languages: javascript, typescript, go, java, rust,
                         csharp, php, ruby.
    """

    @property
    def description(self) -> str:
        return "Removes redundant and placeholder comments"

    def apply(self, cf: CodeFile) -> TransformationResult:
        try:
            if cf.ln_ast is None:
                return self._create_result(cf, cf.content, [])

            comments = cf.ln_ast.get("comments", [])
            if not comments:
                return self._create_result(cf, cf.content, [])

            changes: List[str] = []
            removals: List[Tuple[int, int]] = []

            for comment in comments:
                text = comment.get("text", "")
                if not text.strip():
                    continue

                if _is_redundant_comment(text, cf.language):
                    start = comment.get("start_line", 1)
                    end = comment.get("end_line", start)
                    if not any(r[0] <= start <= r[1] for r in removals):
                        removals.append((start, end))
                        changes.append(f"Removed comment: {text.strip()[:50]}")

            if not removals:
                return self._create_result(cf, cf.content, [])

            # Apply in reverse order
            current = cf.content
            for start, end in sorted(removals, key=lambda x: x[0], reverse=True):
                current = self._remove_lines(current, start, end)

            return self._create_result(cf, current, changes)

        except Exception as e:
            return self._create_error_result(cf, f"RedundantCommentRule failed: {e}")
