"""CLI entry point for the pyneat command.

This is the single entry point registered in [project.scripts] of
pyproject.toml. It delegates to the full CLI implementation in
pyneat_rust/pyneat/cli/cli_impl.py.
"""

import sys


def main() -> int:
    """Entry point for the `pyneat` command.

    This function is registered as the [project.scripts.pyneat] entry
    point in pyproject.toml and is called by the console script
    wrapper generated by pip/setuptools.

    Returns:
        Exit code (0 = success, non-zero = error).
    """
    if sys.version_info < (3, 10):
        sys.stderr.write("Error: pyneat requires Python 3.10 or later.\n")
        return 1

    try:
        from pyneat.cli.cli_impl import cli
        return cli(standalone_mode=False)
    except ImportError as e:
        sys.stderr.write(f"Error: Could not import pyneat CLI: {e}\n")
        sys.stderr.write(
            "This may indicate a broken installation. Try:\n"
            "  pip install --force-reinstall pyneat\n"
        )
        return 1


if __name__ == "__main__":
    sys.exit(main())
