"""Rule for removing AI boilerplate and meaningless placeholder comments.

Copyright (c) 2024-2026 PyNEAT Authors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, contact: license@pyneat.dev
"""

import re
from typing import List, Tuple

from pyneat.core.types import CodeFile, RuleConfig, TransformationResult
from pyneat.rules.base import Rule


class CommentCleaner(Rule):
    """Removes AI boilerplate comments and meaningless placeholder comments.

    Removes:
      - Empty TODO/FIXME/HACK/NOTE/XXX markers
      - AI-generated boilerplate (# Generated by AI, # AI-generated, etc.)
      - Placeholder/incomplete comments (e.g. "# My ideal implementation:", "# ...", "# ____")
      - Stale annotation comments that are just noise
    """

    # Match a line that is ONLY a comment with no meaningful content
    # (empty, or just placeholder chars)
    EMPTY_COMMENT_RE = re.compile(
        r'^\s*#\s*('
        # Empty or whitespace-only
        r'\s*'
        r'|'
        # TODO/FIXME/HACK with nothing useful after
        r'(TODO\s*:?\s*$)'
        r'|(FIXME\s*:?\s*$)'
        r'|(HACK\s*:?\s*$)'
        r'|(NOTE\s*:?\s*$)'
        r'|(XXX\s*:?\s*$)'
        r'|'
        # AI boilerplate
        r'(generated by AI\s*$)'
        r'|(AI-generated\s*$)'
        r'|(created by AI\s*$)'
        r'|(written by AI\s*$)'
        r'|'
        # Placeholder phrases
        r'(my ideal implementation\s*:?\s*$)'
        r'|(my plan\s*:?\s*$)'
        r'|(implementation\s*:?\s*$)'
        r'|(placeholder\s*:?\s*$)'
        r'|(fill in here\s*:?\s*$)'
        r'|(add code here\s*:?\s*$)'
        r'|(write your code here\s*:?\s*$)'
        r'|'
        # Junk filler characters
        r'(\.{3,}\s*$)'
        r'|(_{2,}\s*$)'
        r'|(----+\s*$)'
        r')\s*$',
        re.IGNORECASE,
    )

    # Match TODO/FIXME/HACK with actual content - remove entire line
    TODO_CONTENT_RE = re.compile(
        r'^\s*#.*?(TODO|FIXME|HACK|NOTE|XXX)\s*:\s*.+$',
        re.IGNORECASE | re.MULTILINE,
    )

    # Inline comments with AI boilerplate only — remove entire line
    AI_BOILERPLATE_RE = re.compile(
        r'^\s*#.*(generated by AI|AI-generated|created by AI|written by AI|AI wrote this)'
        r'.*$',
        re.IGNORECASE | re.MULTILINE,
    )

    @property
    def description(self) -> str:
        return (
            "Removes empty TODO/FIXME markers, AI boilerplate comments, "
            "and placeholder comments"
        )

    def apply(self, code_file: CodeFile) -> TransformationResult:
        try:
            changes: List[str] = []
            content = code_file.content

            # 1. Remove lines that are only empty/noisy comments
            new_content, empty_count = self._remove_empty_comments(content)
            if empty_count:
                changes.append(f"Removed {empty_count} empty/noisy comment line(s)")
            content = new_content

            # 2. Remove AI boilerplate lines
            new_content, ai_count = self._remove_ai_boilerplate(content)
            if ai_count:
                changes.append(f"Removed {ai_count} AI boilerplate comment(s)")
            content = new_content

            # 3. Remove TODO/FIXME/HACK comments with actual content
            new_content, todo_count = self._remove_todo_content(content)
            if todo_count:
                changes.append(f"Removed {todo_count} TODO/FIXME comment(s)")
            content = new_content

            return self._create_result(code_file, content, changes)

        except Exception as e:
            return self._create_error_result(
                code_file, f"CommentCleaner failed: {str(e)}"
            )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _remove_empty_comments(self, content: str) -> Tuple[str, int]:
        """Remove comment-only lines that are empty or contain only placeholders."""
        lines = content.split('\n')
        new_lines = []
        removed = 0

        for line in lines:
            if self.EMPTY_COMMENT_RE.match(line):
                removed += 1
            else:
                new_lines.append(line)

        return '\n'.join(new_lines), removed

    def _remove_ai_boilerplate(self, content: str) -> Tuple[str, int]:
        """Remove lines that are AI-boilerplate comments."""
        matches = list(self.AI_BOILERPLATE_RE.finditer(content))
        if not matches:
            return content, 0

        removed = len(matches)
        # Build new content by removing matching lines
        new_lines = []
        last_end = 0
        for m in matches:
            new_lines.append(content[last_end : m.start()])
            last_end = m.end()
        new_lines.append(content[last_end:])
        result = ''.join(new_lines)
        # Clean up double blank lines
        result = re.sub(r'\n{3,}', '\n\n', result)
        return result, removed

    def _remove_todo_content(self, content: str) -> Tuple[str, int]:
        """Remove TODO/FIXME/HACK comments that have actual content."""
        matches = list(self.TODO_CONTENT_RE.finditer(content))
        if not matches:
            return content, 0

        removed = len(matches)
        # Build new content by removing matching lines
        new_lines = []
        last_end = 0
        for m in matches:
            new_lines.append(content[last_end : m.start()])
            last_end = m.end()
        new_lines.append(content[last_end:])
        result = ''.join(new_lines)
        # Clean up double blank lines
        result = re.sub(r'\n{3,}', '\n\n', result)
        return result, removed
