"""Rule for removing redundant expressions that AI code generators commonly produce.

Copyright (c) 2026 PyNEAT Authors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, contact: license@pyneat.dev
"""

from typing import List

import libcst as cst

from pyneat.core.types import CodeFile, RuleConfig, TransformationResult
from pyneat.rules.base import Rule


class RedundantExpressionRule(Rule):
    """Removes redundant expressions commonly generated by AI.

    Simplifies:
      - if x == True / if x is True -> if x
      - if x == False / if x is False -> if not x
      - str(str(x)) -> str(x)  (nested redundant calls)
      - list([x, y]) -> [x, y]
      - tuple((x, y)) -> (x, y)
    """

    @property
    def description(self) -> str:
        return "Removes redundant expressions (== True/False, nested str/ list calls)"

    def apply(self, code_file: CodeFile) -> TransformationResult:
        try:
            content = code_file.content

            # Use cached CST tree if available (RuleEngine pre-parses)
            if hasattr(code_file, 'cst_tree') and code_file.cst_tree is not None:
                tree = code_file.cst_tree
            else:
                try:
                    tree = cst.parse_module(content)
                except Exception:
                    return self._create_result(code_file, content, [])

            transformer = _RedundantTransformer()
            new_tree = tree.visit(transformer)
            new_content = new_tree.code

            return self._create_result(code_file, new_content, transformer.changes)

        except Exception as e:
            return self._create_error_result(
                code_file, f"RedundantExpressionRule failed: {str(e)}"
            )


# ----------------------------------------------------------------------
# LibCST Transformer
# ----------------------------------------------------------------------


class _RedundantTransformer(cst.CSTTransformer):
    """Transformer that removes redundant expressions."""

    def __init__(self):
        super().__init__()
        self.changes: List[str] = []

    def leave_Comparison(self, original: cst.Comparison,
                          updated: cst.Comparison) -> cst.BaseExpression:
        """Simplify redundant comparisons like x == True, x == False."""
        result = self._simplify_comparison(updated)
        if result is not None:
            self.changes.append(f"Simplified redundant comparison")
            return result
        return updated

    def _simplify_comparison(self, comp: cst.Comparison) -> cst.BaseExpression | None:
        """Convert 'x == True' -> 'x', 'x == False' -> 'not x', etc.

        IMPORTANT: We intentionally skip 'x is True' and 'x is False'
        because they check *identity* (only the exact True/False object),
        NOT truthiness. Converting 'x is True' to 'x' changes behavior for
        truthy-but-not-True values (e.g. 1, "hello", []).
        """
        if len(comp.comparisons) != 1:
            return None

        target = comp.comparisons[0]
        op = target.operator
        left = comp.left
        right = target.comparator

        # Only handle == / != comparisons, NOT is / is not.
        # 'x is True' / 'x is False' are NOT redundant because they
        # check identity, not truthiness.
        if not isinstance(op, cst.Equal) and not isinstance(op, cst.NotEqual):
            return None

        # x == True  ->  x
        if self._is_true_literal(right):
            return left
        # x == False  ->  not x
        if self._is_false_literal(right):
            return cst.UnaryOperation(
                operator=cst.Not(),
                expression=left,
            )
        # False == x  ->  not x  (only for ==)
        if self._is_false_literal(left) and isinstance(op, cst.Equal):
            return cst.UnaryOperation(operator=cst.Not(), expression=right)
        # True == x  ->  x  (only for ==)
        if self._is_true_literal(left) and isinstance(op, cst.Equal):
            return right

        return None

    def _is_true_literal(self, node: cst.BaseExpression) -> bool:
        """Check if node is the literal True (handles both old and new libcst)."""
        if isinstance(node, cst.Name):
            return node.value == 'True'
        # For newer libcst that uses Constant nodes
        if hasattr(cst, 'Constant') and isinstance(node, getattr(cst, 'Constant', None)):
            return getattr(node.value, 'value', None) is True
        return False

    def _is_false_literal(self, node: cst.BaseExpression) -> bool:
        """Check if node is the literal False (NOT None - use IsNotNoneRule for that)."""
        if isinstance(node, cst.Name):
            return node.value == 'False'
        # For newer libcst that uses Constant nodes
        if hasattr(cst, 'Constant') and isinstance(node, getattr(cst, 'Constant', None)):
            val = getattr(node.value, 'value', None)
            return val is False
        return False

    def leave_Call(self, original: cst.Call, updated: cst.Call) -> cst.BaseExpression:
        """Simplify redundant nested calls like str(str(x)), list([...])."""
        result = self._simplify_nested_call(updated)
        if result is not None:
            self.changes.append("Simplified redundant nested call")
            return result
        return updated

    def _simplify_nested_call(self, call: cst.Call) -> cst.BaseExpression | None:
        """Handle str(str(x)), list([...]), tuple((...) )."""
        func = call.func
        if not isinstance(func, cst.Name):
            return None

        outer_name = func.value

        # str(str(x)) -> str(x), list(list(x)) -> list(x)
        if len(call.args) == 1 and outer_name in ('str', 'repr', 'int', 'float', 'bytes', 'oct', 'hex'):
            arg = call.args[0].value
            if isinstance(arg, cst.Call) and isinstance(arg.func, cst.Name):
                if arg.func.value == outer_name and len(arg.args) == 1:
                    return cst.Call(func=cst.Name(outer_name), args=arg.args)

        # list([...]) -> [...]
        if outer_name == 'list' and len(call.args) == 1:
            arg_val = call.args[0].value
            if isinstance(arg_val, cst.List):
                return arg_val

        # tuple((...)) -> (...)
        if outer_name == 'tuple' and len(call.args) == 1:
            arg_val = call.args[0].value
            if isinstance(arg_val, cst.Tuple):
                return arg_val

        # set({...}) -> {...}
        if outer_name == 'set' and len(call.args) == 1:
            arg_val = call.args[0].value
            if isinstance(arg_val, cst.Set):
                return arg_val

        return None
