"""GitHub API client for downloading Python files from popular repos.

Copyright (c) 2026 PyNEAT Authors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, contact: khanhnam.copywriting@gmail.com

Uses the GitHub REST API (unauthenticated or with a PAT) to:
- List all .py files in a repo's default branch
- Download raw file content
- Respect rate limits with automatic backoff
"""

from __future__ import annotations

import os
import time
import urllib.request
import urllib.error
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, Iterator, List, Optional, Tuple

import json  # stdlib only — no requests dependency required


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# GitHub API base URL
GITHUB_API = "https://api.github.com"
# Raw file URL template
RAW_URL_TEMPLATE = "https://raw.githubusercontent.com/{owner}/{repo}/{sha}/{path}"

# Max file size (512 KB) — skip generated/binary files
MAX_FILE_BYTES = 512 * 1024

# Files to skip (generated, test infra, build artifacts)
SKIP_PATTERNS = frozenset({
    "__pycache__", ".pyc", ".pyo", ".pyd",
    "setup.py", "setup.cfg",  # generated by setuptools
    "conftest.py",             # pytest infrastructure
    "noxfile.py",              # nox test runner config
    "toxfile.py",              # tox config
    ".tox", ".nox",
    "MANIFEST.in",
    ".coveragerc", ".codecov.yml",
    "bindata_asset.py",        # generated by pybind11
    "versioneer.py",           # generated by versioneer
})

# Safe repos that are known to have good Python code
SAFE_REPOS = frozenset({
    "django", "requests", "flask", "fastapi", "numpy", "pandas",
    "scikit-learn", "twisted", "airflow", "ansible", "black", "pytest",
    "cpython", "thealgorithms", "public-apis",
})


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

@dataclass
class GitHubFile:
    """A Python file discovered in a GitHub repo."""

    repo: str           # e.g. "django/django"
    path: str           # e.g. "django/db/models/query.py"
    sha: str            # Git blob SHA
    size: int           # bytes
    url: str            # API URL for this file
    raw_url: str        # Raw content URL


@dataclass
class GitHubStats:
    """Statistics from a fuzz run's GitHub interactions."""

    repos_tested: int = 0
    files_discovered: int = 0
    files_downloaded: int = 0
    api_calls: int = 0
    rate_limit_remaining: int = 0
    rate_limit_reset: Optional[int] = None  # Unix timestamp
    errors: List[str] = field(default_factory=list)
    skipped_files: int = 0
    total_bytes_downloaded: int = 0


@dataclass
class CachedFiles:
    """Cache of downloaded file content for resume support."""

    files: List[Tuple[GitHubFile, str]] = field(default_factory=list)
    repo: str = ""
    saved_at: str = ""


# ---------------------------------------------------------------------------
# GitHubClient
# ---------------------------------------------------------------------------

class GitHubClient:
    """Lightweight GitHub API client for fuzz testing.

    Handles:
    - Authentication (optional PAT)
    - Rate limit detection and backoff
    - Recursive file listing
    - Raw file downloading with encoding fallbacks

    Example:
        client = GitHubClient(token="ghp_xxxx")
        for file in client.list_py_files("django/django"):
            content = client.download_file(file)
            print(file.path, len(content))
    """

    def __init__(self, token: Optional[str] = None):
        self._token = token or os.environ.get("GITHUB_TOKEN", "") or os.environ.get("GITHUB_API_TOKEN", "")
        self._stats = GitHubStats()
        self._request_count = 0
        self._last_rate_limit_reset: Optional[int] = None

    # ------------------------------------------------------------------
    # HTTP helpers
    # ------------------------------------------------------------------

    def _request(self, url: str, headers: Optional[Dict[str, str]] = None) -> Tuple[int, Dict, bytes]:
        """Make an HTTP request and return (status_code, headers, body).

        Returns headers as a dict (lowercase keys) for easy access.
        """
        h = headers or {}
        if self._token:
            h["Authorization"] = f"token {self._token}"
        h["Accept"] = "application/vnd.github.v3+json"
        h["User-Agent"] = "PyNeat-Fuzz/1.0"

        req = urllib.request.Request(url, headers=h)
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                raw_headers = dict(resp.headers)
                headers_lower = {k.lower(): v for k, v in raw_headers.items()}
                return resp.status, headers_lower, resp.read()
        except urllib.error.HTTPError as e:
            raw_headers = dict(e.headers)
            headers_lower = {k.lower(): v for k, v in raw_headers.items()}
            return e.code, headers_lower, b""
        except urllib.error.URLError:
            return 0, {}, b""

    def _check_rate_limit(self, headers: Dict[str, str]) -> None:
        """Check and handle rate limit headers."""
        if "x-ratelimit-remaining" in headers:
            remaining = int(headers["x-ratelimit-remaining"])
            self._stats.rate_limit_remaining = remaining
            self._stats.api_calls += 1

        if "x-ratelimit-reset" in headers:
            self._last_rate_limit_reset = int(headers["x-ratelimit-reset"])
            self._stats.rate_limit_reset = self._last_rate_limit_reset

        # If we're close to the limit, back off
        if self._stats.rate_limit_remaining < 10 and self._stats.rate_limit_reset:
            reset_time = datetime.fromtimestamp(self._stats.rate_limit_reset, tz=timezone.utc)
            wait_seconds = (reset_time - datetime.now(timezone.utc)).total_seconds()
            if wait_seconds > 0:
                print(f"\n[GitHub rate limit low ({remaining}), waiting {wait_seconds:.0f}s...]")
                time.sleep(min(wait_seconds + 1, 60))

    def _api(self, path: str) -> dict:
        """Make an authenticated GitHub API request and return JSON."""
        url = f"{GITHUB_API}{path}"
        status, headers, body = self._request(url)
        self._check_rate_limit(headers)

        if status == 200:
            return json.loads(body.decode("utf-8", errors="replace"))
        elif status == 403:
            if "rate limit exceeded" in body.decode(errors="replace").lower():
                # Wait for reset
                if self._last_rate_limit_reset:
                    wait = max(1, self._last_rate_limit_reset - int(time.time()) + 1)
                    print(f"\n[RATE LIMIT EXCEEDED — waiting {wait}s]")
                    time.sleep(min(wait, 120))
            self._stats.errors.append(f"403 for {path}")
            return {}
        elif status == 404:
            self._stats.errors.append(f"404 not found: {path}")
            return {}
        else:
            self._stats.errors.append(f"HTTP {status} for {path}")
            return {}

    # ------------------------------------------------------------------
    # Repo / file discovery
    # ------------------------------------------------------------------

    def get_default_branch(self, owner: str, repo: str) -> str:
        """Get the default branch name for a repo."""
        data = self._api(f"/repos/{owner}/{repo}")
        return data.get("default_branch", "main")

    def list_py_files(self, repo: str, max_files: int = 200) -> Iterator[GitHubFile]:
        """List all Python files in a repo's default branch.

        Uses the recursive tree API to get all files efficiently.
        Yields GitHubFile objects.
        """
        self._stats.repos_tested += 1
        owner, repo_name = repo.split("/", 1)

        try:
            branch = self.get_default_branch(owner, repo_name)
            tree_data = self._api(f"/repos/{owner}/{repo_name}/git/trees/{branch}?recursive=1")
        except Exception as e:
            self._stats.errors.append(f"Failed to list files for {repo}: {e}")
            return

        tree = tree_data.get("tree", [])
        count = 0

        for item in tree:
            if item.get("type") != "blob":
                continue
            path = item.get("path", "")
            if not path.endswith(".py"):
                continue

            # Skip known noise files
            if any(skip in path for skip in SKIP_PATTERNS):
                continue

            size = item.get("size", 0)
            if size > MAX_FILE_BYTES:
                self._stats.skipped_files += 1
                continue

            if count >= max_files:
                break

            file_obj = GitHubFile(
                repo=repo,
                path=path,
                sha=item.get("sha", ""),
                size=size,
                url=item.get("url", ""),
                raw_url=RAW_URL_TEMPLATE.format(
                    owner=owner, repo=repo_name, sha=branch, path=path
                ),
            )
            count += 1
            self._stats.files_discovered += 1
            yield file_obj

    # ------------------------------------------------------------------
    # File downloading
    # ------------------------------------------------------------------

    def download_file(self, gh_file: GitHubFile) -> Optional[str]:
        """Download the raw content of a GitHubFile.

        Uses the raw GitHub URL (no auth needed for public repos).
        Falls back to API if raw URL fails.
        Returns the file content as a string, or None on failure.
        """
        content: Optional[str] = None
        url = gh_file.raw_url

        # Try raw URL first
        try:
            req = urllib.request.Request(url)
            req.add_header("User-Agent", "PyNeat-Fuzz/1.0")
            req.add_header("Accept", "text/plain, text/x-python, */*")
            with urllib.request.urlopen(req, timeout=30) as resp:
                raw_body = resp.read()
                content = raw_body.decode("utf-8", errors="replace")
                self._stats.total_bytes_downloaded += len(raw_body)
                self._stats.files_downloaded += 1
        except Exception:
            # Fall back to GitHub API
            url = gh_file.url

        if content is None:
            try:
                status, headers, body = self._request(url)
                if status == 200:
                    import base64
                    # GitHub API returns base64-encoded content
                    if "content" in headers.get("content-type", ""):
                        # response is base64
                        decoded = base64.b64decode(body)
                        content = decoded.decode("utf-8", errors="replace")
                    else:
                        content = body.decode("utf-8", errors="replace")
                    self._stats.files_downloaded += 1
            except Exception as e:
                self._stats.errors.append(f"Failed to download {gh_file.path}: {e}")
                return None

        return content

    @property
    def stats(self) -> GitHubStats:
        return self._stats


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------

def download_repos_py_files(
    repos: List[str],
    max_files_per_repo: int = 200,
    token: Optional[str] = None,
    on_progress: Optional[callable] = None,
) -> Iterator[Tuple[str, GitHubFile, str]]:
    """Download Python files from multiple repos.

    Yields (repo, GitHubFile, content) tuples as files are downloaded.

    Example:
        for repo, gh_file, content in download_repos_py_files(
            ["django/django", "psf/requests"],
            max_files_per_repo=50,
        ):
            print(f"{repo}/{gh_file.path}: {len(content)} bytes")
    """
    client = GitHubClient(token=token)

    for repo in repos:
        owner, repo_name = repo.split("/", 1)
        print(f"[GitHub] Fetching {repo}...")

        try:
            file_count = 0
            for gh_file in client.list_py_files(repo, max_files=max_files_per_repo):
                content = client.download_file(gh_file)
                if content is not None:
                    # Basic validation — must be valid-ish Python
                    if _looks_like_python(content):
                        file_count += 1
                        if on_progress:
                            on_progress(repo, gh_file.path, file_count)
                        yield repo, gh_file, content
        except Exception as e:
            print(f"[GitHub] Error fetching {repo}: {e}")


def _looks_like_python(content: str) -> bool:
    """Heuristic: does this look like Python source code?"""
    # Skip very short or binary-looking content
    if len(content) < 10:
        return False
    # Skip files that are clearly not Python
    non_python_indicators = ["<?xml", "<!DOCTYPE", "<?php", "<html", "package-lock.json"]
    for indicator in non_python_indicators:
        if content.strip().startswith(indicator):
            return False
    return True


def save_cache(cached: CachedFiles, path: Path) -> None:
    """Save a cache of downloaded files to a JSON file."""
    data = {
        "repo": cached.repo,
        "saved_at": datetime.now(timezone.utc).isoformat(),
        "files": [
            {"path": gh_file.path, "sha": gh_file.sha, "content": content}
            for gh_file, content in cached.files
        ],
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


def load_cache(path: Path) -> Optional[CachedFiles]:
    """Load a cached file list from a JSON file."""
    if not path.exists():
        return None
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        files = []
        for item in data.get("files", []):
            gh_file = GitHubFile(
                repo=data.get("repo", ""),
                path=item["path"],
                sha=item["sha"],
                size=len(item["content"]),
                url="",
                raw_url="",
            )
            files.append((gh_file, item["content"]))
        return CachedFiles(files=files, repo=data.get("repo", ""), saved_at=data.get("saved_at", ""))
    except Exception:
        return None